### PR TITLE
Add packages for Af&Rica Android application

### PR DESCRIPTION
**Pull request by benoit74**
Fix https://github.com/offspot/package-requests/issues/44

Adding the three languages of Af&Rica application.

Zip files created manually with custom homepage "f-droid like".

Nota: while Android package name is `com.AfRica.DCX`, I've chosen a slightly better `ident` with less risks of collision (pretty sure `africa.com` is not owned by Orange).

### CODE REVIEW

**Comment by benoit74** [comment]
@Popolechien can you please double check descriptions are OK?

**Comment by Popolechien** [comment]
@benoit74 Small typo: `les cultures Africaines` > `les cultures africaines` as in French adjectives are never upper cased.

**Review by rgaudin — CHANGES_REQUESTED** [review]
Catalog entries look OK but the ZIPs are incorrect. There should be no wrapping folder.

```sh
❯ unzip -l af_and_rica_ar_1.0.0.zip
Archive:  af_and_rica_ar_1.0.0.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  12-06-2024 07:23   af_and_rica_ar/
      313  12-06-2024 07:23   __MACOSX/._af_and_rica_ar
     1714  12-16-2024 13:33   af_and_rica_ar/index.html
      269  12-16-2024 13:33   __MACOSX/af_and_rica_ar/._index.html
     6148  12-16-2024 13:30   af_and_rica_ar/.DS_Store
      120  12-16-2024 13:30   __MACOSX/af_and_rica_ar/._.DS_Store
        0  12-16-2024 13:27   af_and_rica_ar/download/
      213  12-16-2024 13:27   __MACOSX/af_and_rica_ar/._download
        0  12-06-2024 07:26   af_and_rica_ar/assets/
      213  12-06-2024 07:26   __MACOSX/af_and_rica_ar/._assets
     6148  12-16-2024 13:25   af_and_rica_ar/download/.DS_Store
      120  12-16-2024 13:25   __MACOSX/af_and_rica_ar/download/._.DS_Store
 46429593  12-16-2024 13:05   af_and_rica_ar/download/com.AfRica.DCX_1.0.0.apk
      634  12-16-2024 13:05   __MACOSX/af_and_rica_ar/download/._com.AfRica.DCX_1.0.0.apk
    16367  12-06-2024 07:22   af_and_rica_ar/assets/icon.png
      589  12-06-2024 07:22   __MACOSX/af_and_rica_ar/assets/._icon.png
     6148  12-06-2024 07:26   af_and_rica_ar/assets/.DS_Store
      120  12-06-2024 07:26   __MACOSX/af_and_rica_ar/assets/._.DS_Store
    27558  01-10-2024 11:37   af_and_rica_ar/assets/main.css
      269  01-10-2024 11:37   __MACOSX/af_and_rica_ar/assets/._main.css
    32652  01-10-2024 11:34   af_and_rica_ar/assets/roboto.ttf
      213  01-10-2024 11:34   __MACOSX/af_and_rica_ar/assets/._roboto.ttf
---------                     -------
 46529401                     22 files

❯ unzip -l com.kylecorry.trail_sense_111.zip
Archive:  com.kylecorry.trail_sense_111.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  01-10-2024 11:59   assets/
    24800  01-10-2024 11:36   assets/icon.png
    27558  01-10-2024 11:37   assets/main.css
    32652  01-10-2024 11:34   assets/roboto.ttf
        0  01-10-2024 11:42   download/
  7082356  01-10-2024 11:41   download/com.kylecorry.trail_sense_111.apk
     3321  01-10-2024 12:08   index.html
---------                     -------
  7170687                     7 files
```

**Comment by benoit74** [comment]
And no stupid hidden __MACOSX folders ^^

**Comment by benoit74** [comment]
Just made changes to the ZIM files, and obviously to the catalog since sizes / md5sum have changed

**Comment by benoit74** [comment]
I pushed some doc to https://github.com/offspot/overview/wiki/Android-App-Creation-Guide#configuration (mainly to not have to search for zip arguments again ^^)

**Comment by rgaudin** [comment]
Thank you ; I forgot to mention ZIP should not be compressed. I updated the doc, recreated the ZIPs and updated the JSON. I also added the entry to the Changelog.

**Review by rgaudin — APPROVED** [review]

**Pull request merged**
