### PR TITLE
Updated app description to clarify they're downloadable APKs

### PR DESCRIPTION
**Pull request by Popolechien**
Fixed at Survival Manual, Trail Sense, and Bible apps

### CODE REVIEW

**Comment by rgaudin** [comment]
Shouldn't we use a tag instead? @kelson42 WDYT?

**Comment by Popolechien** [comment]
@rgaudin There's already a tag but it's fairly small/discrete

**Comment by rgaudin** [comment]
> @rgaudin There's already a tag but it's fairly small/discrete

I feel like Adding that to the description is not the right approach. We can imagine displaying that tag differently. Do you want to run this by @siemsie and let me know?

**Comment by Popolechien** [comment]
@rgaudin will do but changing to design elements is a much heavier process. This here is just a quick wording fix.

**Comment by rgaudin** [comment]
Doing it wrong because it's quicker is not always the wisest.

In this case, as it's in the catalog and the catalog is bundled in the software, it's the same process as updating the dashboard.
If all it takes is changing the color/shape/label of the task ; the effort and time to production is equivalent. If it's not, then we'll have a ticket with the way forward and we can implement this as a transition.

**Pull request merged**
